### PR TITLE
Bump electron version to 1.8.8

### LINKED ISSUE #57: Bump electron to 1.8.8
screen shot 2018-08-24 at 10 11 38 am

### PR DESCRIPTION
**Pull request by BenEmdon**
Fixes #57 

- [x] Merge after #47

### CODE REVIEW

**Comment by BenEmdon** [comment]
Unsure why AppVeyor is failing. Might anyone know?

**Comment by shiftkey** [comment]
@BenEmdon you need to add the `appveyor.yml` file from #47 to this PR to avoid the default behaviour https://github.com/education/classroom-desktop/pull/47/files#diff-11c909939117928998b102a1fff7d363 (I think it'll actually skip the build, but that's okay, @srinjoym can confirm)

**Comment by srinjoym** [comment]
@BenEmdon  Still setting up appveyor + travis builds on that branch for deployment, let me get that setup today, just so we don't get merge conflicts with an out of date `appveyor.yml`

**Comment by BenEmdon** [comment]
@srinjoym sounds good 👌 I'll wait for #47 to merge

**Pull request merged**
